stages:
  - prepare
  - tests
  - build
  - release

composer:
  stage: prepare
  image: thecodingmachine/php:8.1-v4-cli-node16
  script:
    - php -v
    - composer config -g cache-dir "$CI_PROJECT_DIR/.composer-cache"
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
  artifacts:
    paths:
      - vendor/
    expire_in: 30 days
    when: on_success
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .composer-cache

.test-php8.0:
  stage: tests
  image: thecodingmachine/php:8.0-v4-cli-node16
  dependencies: []
  before_script:
    - sudo apt-get update
    - sudo apt-get install -y make
    - sudo chown -R docker:docker .scenarios.lock/

.test-php8.1:
  stage: tests
  image: thecodingmachine/php:8.1-v4-cli-node16
  dependencies: []
  before_script:
    - sudo apt-get update
    - sudo apt-get install -y make
    - sudo chown -R docker:docker .scenarios.lock/

test-sf3-8.0:
  extends: .test-php8.0
  script:
    - make test-sf3

test-sf4-8.0:
  extends: .test-php8.0
  script:
    - make test-sf4

test-sf5-8.0:
  extends: .test-php8.0
  script:
    - make test-sf5

test-sf6-8.0:
  extends: .test-php8.0
  script:
    - make test-sf6

test-8.0:
  extends: .test-php8.0
  script:
    - make test-sf

test-sf3-8.1:
  extends: .test-php8.1
  script:
    - make test-sf3

test-sf4-8.1:
  extends: .test-php8.1
  script:
    - make test-sf4

test-sf5-8.1:
  extends: .test-php8.1
  script:
    - make test-sf5

test-sf6-8.1:
  extends: .test-php8.1
  script:
    - make test-sf6

test-8.1:
  extends: .test-php8.1
  script:
    - make test-sf

phar:
  stage: build
  image: jakzal/phpqa:alpine
  script:
    - box compile
  artifacts:
    paths:
      - ./faker.phar

github:
  stage: release
  image: node:lts-stretch
  script:
    - git remote set-url origin "https://github.com/morawskim/faker-cli.git"
    - npm ci
    - npx release-it --no-git --no-increment
  only:
    - tags
  except:
    - branches
